### ISSUE TITLE
message: 'Error: no model file given.', type: 'exit', code: 1

### ISSUE THREAD

**Issue by NKJay** [MiniZinc/minizinc-js#31]
Hi，
I found this issue when I using 4.3.1 version of this lib. And I tried to add some log in the compressed code 'minizinc-node.mjs'.
I found the file name isn't added to _toRun list correctly.
![image](https://github.com/MiniZinc/minizinc-js/assets/15214157/ae41bdb0-3a8c-412b-895a-449562cbabf9)

I also tried to copy 'node.js' file to my local environment and replaced packaged lib. With the same code. It works good. Seems like there might be wrong somewhere. Perhaps needto release a new version?

**Comment by cyderize** [comment]
Thanks, I just published a new version, could you check if it works now?

**Comment by NKJay** [comment]
Yes. It works now. Thanks
